logging:
  level:
    org.springframework.security: DEBUG


server:
  port: 8083
  servlet:
    context-path: /techgeeknext
    session:
      cookie:
        path: /techgeeknext
  ssl:
    key-store-password: techgeeknext123
    key-store: classpath:securitykeystore.p12
    key-store-type: PKCS12
    key-alias: techgeeknext-alias




spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 965999691956-p90targvpar84ahoppos3c11lqcab4e8.apps.googleusercontent.com
            client-secret: eioNq1OB9uWoWVkxwScSu40u
            scope: profile,email,https://www.googleapis.com/auth/calendar
            client-name: TechGeekNextOAuthWebClient
  datasource:
    url: jdbc:mysql://localhost/SecuritySchema?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 
    platform: mysql
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update